# Generated by Django 5.0.1 on 2024-01-25 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('species', models.CharField(max_length=40)),
                ('date_purchase', models.DateField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('watering_frequency', models.DurationField()),
                ('water_requirement', models.DecimalField(decimal_places=3, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner plant')),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
            },
        ),
        migrations.CreateModel(
            name='Watering',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_valid', models.BooleanField(default=False)),
                ('date_planned', models.DateTimeField()),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watering_history', to='plant_manage.plant')),
            ],
            options={
                'verbose_name': 'Watering',
                'verbose_name_plural': 'Waterings',
            },
        ),
    ]
