# Generated by Django 5.0.1 on 2024-01-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='date_purchase',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='watering',
            name='date_planned',
            field=models.DateTimeField(blank=True),
        ),
    ]
